# Generated by Django 5.1.2 on 2024-10-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booking_date',
        ),
        migrations.AddField(
            model_name='eventapp',
            name='organizer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventapp',
            name='category',
            field=models.CharField(choices=[('Job Fair', 'Job Fair'), ('Discussion', 'Discussion'), ('Party', 'Party')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventapp',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='eventapp',
            name='end_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventapp',
            name='start_date_time',
            field=models.DateTimeField(),
        ),
    ]
