# Generated by Django 5.1.2 on 2024-10-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_rename_created_at_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapp',
            name='category',
            field=models.CharField(choices=[('Job Fair', 'Job Fair'), ('Discussion', 'Discussion'), ('Party', 'Party'), ('Book Fair', 'Book Fair'), ('Others', 'Others')], max_length=50),
        ),
    ]
