# Generated by Django 5.1.2 on 2024-10-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_name'),
        ('event_app', '0003_alter_eventapp_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapp',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
