# Generated by Django 5.1.2 on 2024-10-29 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_alter_eventapp_category'),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapp',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.organizer'),
        ),
    ]
