# Generated by Django 5.1.2 on 2024-10-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Job Fair', 'Job Fair'), ('Discussion', 'Discussion'), ('party', 'Party')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
