# Generated by Django 5.1.2 on 2024-10-26 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_category_alter_event_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booking_date',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'event')},
        ),
    ]
